name: ci-workflow
on: [push]
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.2.0
      with:
        go-version: ~1.17.7
    - run: go build
